{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.dovehome",
    "module": "bakalib",
    "version": "1.0.0.23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "bakalib-1.0.0.23.jar",
          "url": "bakalib-1.0.0.23.jar",
          "size": 31712,
          "sha512": "2216907316cfdc5e70d96e0757b4983cb311ead6e2603a293ba67ab131eb5757549ab8b3f0115ead9d33af878de258696d73e1e58be0a8b9622ca572c5bb6c2b",
          "sha256": "553e60cfce04316573162c23d776aa67a3f85aa7c9c73d8ee83c54346c90801e",
          "sha1": "6aa48174c3d0f1bc47e643974dd6f58fb6ddbcee",
          "md5": "2c846823267cfdd156a890d5edd717fd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "bakalib-1.0.0.23.jar",
          "url": "bakalib-1.0.0.23.jar",
          "size": 31712,
          "sha512": "2216907316cfdc5e70d96e0757b4983cb311ead6e2603a293ba67ab131eb5757549ab8b3f0115ead9d33af878de258696d73e1e58be0a8b9622ca572c5bb6c2b",
          "sha256": "553e60cfce04316573162c23d776aa67a3f85aa7c9c73d8ee83c54346c90801e",
          "sha1": "6aa48174c3d0f1bc47e643974dd6f58fb6ddbcee",
          "md5": "2c846823267cfdd156a890d5edd717fd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "bakalib-1.0.0.23-sources.jar",
          "url": "bakalib-1.0.0.23-sources.jar",
          "size": 21028,
          "sha512": "755d030d701a21e8bf3cf60587ea3be8221a339f5f82df7dae8fe30bb4e2ac3e9d79f9079cc448c2eb2280c18471a22f83aa52a23374de12ca3c95f0291cae5b",
          "sha256": "1482be8f76d2f0e92644189bc3869eb1d09fbf911d39708d5b99ad567033c937",
          "sha1": "b3236e7193518768067d2c9ed7f3e138dcb324b8",
          "md5": "4ab53c85ce52266a163011808dfe2868"
        }
      ]
    }
  ]
}
