{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.dovehome",
    "module": "dovehomemod",
    "version": "1.0.0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.architectury",
          "module": "architectury-forge",
          "version": {
            "requires": "6.5.85"
          }
        }
      ],
      "files": [
        {
          "name": "dovehomemod-1.0.0.9.jar",
          "url": "dovehomemod-1.0.0.9.jar",
          "size": 5700085,
          "sha512": "863d93058666780076d5427786aeb96bf03227597a033be23d8daec752237012a2cfbe595dca2ccf02714860757ccfe675a38567150b01afe0ea235bf0a7741b",
          "sha256": "de74b893ae67a700a45fb91e7fe81a74b4eafee37e1390627ec8326e59f6130a",
          "sha1": "ea62217212158c09cc90b2f2a9515e52ac3c1934",
          "md5": "d6d55a2bc66adafc4d121e824b556c91"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-common",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-forge",
          "version": {
            "requires": "6.5.85"
          }
        },
        {
          "group": "software.bernie.geckolib",
          "module": "geckolib-forge-1.19",
          "version": {
            "requires": "3.1.40"
          }
        },
        {
          "group": "de.ellpeck.naturesaura",
          "module": "NaturesAura",
          "version": {
            "requires": "38.2.217"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "vazkii.patchouli",
          "module": "Patchouli",
          "version": {
            "requires": "1.19.2-77"
          }
        },
        {
          "group": "vazkii.botania",
          "module": "Botania",
          "version": {
            "requires": "1.19.2-440-FORGE"
          }
        },
        {
          "group": "top.theillusivec4.curios",
          "module": "curios-forge",
          "version": {
            "requires": "1.19.2-5.1.4.3"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-forge",
          "version": {
            "requires": "1902.6.2-build.42"
          }
        },
        {
          "group": "io.github.dovehome",
          "module": "bakalib",
          "version": {
            "requires": "1.0.0.21"
          }
        },
        {
          "group": "curse.maven",
          "module": "citadel-331936",
          "version": {
            "requires": "4556677"
          }
        }
      ],
      "files": [
        {
          "name": "dovehomemod-1.0.0.9.jar",
          "url": "dovehomemod-1.0.0.9.jar",
          "size": 5700085,
          "sha512": "863d93058666780076d5427786aeb96bf03227597a033be23d8daec752237012a2cfbe595dca2ccf02714860757ccfe675a38567150b01afe0ea235bf0a7741b",
          "sha256": "de74b893ae67a700a45fb91e7fe81a74b4eafee37e1390627ec8326e59f6130a",
          "sha1": "ea62217212158c09cc90b2f2a9515e52ac3c1934",
          "md5": "d6d55a2bc66adafc4d121e824b556c91"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dovehomemod-1.0.0.9-sources.jar",
          "url": "dovehomemod-1.0.0.9-sources.jar",
          "size": 107244,
          "sha512": "02a2332b7b139149dfa8168c794260c015e8dbc0695f7a75900870010ad6f177302e46eb5a6b2f254d7d6d37df9a895ba2845a201311e85dd332066fce258ee9",
          "sha256": "b3200e19099ab5bdb1951956bc315177719b0c98468e5add6380dc7ed1c7271a",
          "sha1": "1c68c8fcf630d52bfbb2275cdb013a15ef9916d4",
          "md5": "d4d21170c4ca09c54cf354db9fb00180"
        }
      ]
    }
  ]
}
