{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.dovehome",
    "module": "dovehomemodcore",
    "version": "1.0.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dovehomemodcore-1.0.0.0.jar",
          "url": "dovehomemodcore-1.0.0.0.jar",
          "size": 5673636,
          "sha512": "0c3928717cfb47b3966a1fcd9189e2eb9c9964c58758cf78a649810741af241e3272dfee57e8127d632316c2670d89f8dab51ef21b91a55340ff4fc3fc8cb241",
          "sha256": "459eae8432b9bc3fee70fc4ce0a61d5021c48efbc75eec9323c64e969885bb1a",
          "sha1": "c75332625d591ae35e162e2a9c0ca1d9ea131e45",
          "md5": "91cf500cf9f408ee60592082b248527a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.dovehome",
          "module": "dovehomemod",
          "version": {
            "requires": "1.0.0.9"
          }
        }
      ],
      "files": [
        {
          "name": "dovehomemodcore-1.0.0.0.jar",
          "url": "dovehomemodcore-1.0.0.0.jar",
          "size": 5673636,
          "sha512": "0c3928717cfb47b3966a1fcd9189e2eb9c9964c58758cf78a649810741af241e3272dfee57e8127d632316c2670d89f8dab51ef21b91a55340ff4fc3fc8cb241",
          "sha256": "459eae8432b9bc3fee70fc4ce0a61d5021c48efbc75eec9323c64e969885bb1a",
          "sha1": "c75332625d591ae35e162e2a9c0ca1d9ea131e45",
          "md5": "91cf500cf9f408ee60592082b248527a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dovehomemodcore-1.0.0.0-sources.jar",
          "url": "dovehomemodcore-1.0.0.0-sources.jar",
          "size": 5804,
          "sha512": "fbf3d1d88e4b859cdd8646cccf1236a185aab8225466e642ad6c7742b0549668a74d16fbfe89d49d29a2cf5bb719dc8cd9d332e5b68a97799f7d7b4511aac9b3",
          "sha256": "95e31886931ea966310e2f4cde35383654642bd729536127d5b5d4d4578e8f86",
          "sha1": "867d8785236c9c6c8b96af81b970b894c64110ef",
          "md5": "6a5789ba4cb9de2008c2e7cec0008c43"
        }
      ]
    }
  ]
}
