{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.dovehome",
    "module": "dovehomemodcore",
    "version": "1.0.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dovehomemodcore-1.0.0.0.jar",
          "url": "dovehomemodcore-1.0.0.0.jar",
          "size": 233961,
          "sha512": "08df8b27a1f3ec2b03b97548db16a0ce8540824d81dd942cb74e37681f41bc136798ba8312bcdb47800200e4ad9079c1abed8a6b819223a57e979998e911af61",
          "sha256": "b4c57a02eeb2d3ddf91b7866c178ffb40a8dce51d3c947e508dc81ac64f79c61",
          "sha1": "7ce7043d8b3cbdba0050c86374780598c66f367c",
          "md5": "e44e93f6748dba856d5c172f6b0582db"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.dovehome",
          "module": "dovehomemod",
          "version": {
            "requires": "1.0.0.8"
          }
        }
      ],
      "files": [
        {
          "name": "dovehomemodcore-1.0.0.0.jar",
          "url": "dovehomemodcore-1.0.0.0.jar",
          "size": 233961,
          "sha512": "08df8b27a1f3ec2b03b97548db16a0ce8540824d81dd942cb74e37681f41bc136798ba8312bcdb47800200e4ad9079c1abed8a6b819223a57e979998e911af61",
          "sha256": "b4c57a02eeb2d3ddf91b7866c178ffb40a8dce51d3c947e508dc81ac64f79c61",
          "sha1": "7ce7043d8b3cbdba0050c86374780598c66f367c",
          "md5": "e44e93f6748dba856d5c172f6b0582db"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dovehomemodcore-1.0.0.0-sources.jar",
          "url": "dovehomemodcore-1.0.0.0-sources.jar",
          "size": 5994,
          "sha512": "4b297d5989ceb4d10daacd3717cfb4f2c73e19b93a79a0b663ddc3172e2cf95a2881f08c620dfd8ad51dab3499c42a82b6488d5075e9359ea5f2e2ebfa7eabe2",
          "sha256": "38fbe4d1613690ff8ba6e5ba293aa9b448560721f365da07e3e535c77a59ea83",
          "sha1": "ab3e2f8c9c98e9a8cdd6dc00b103d7dc1b6d4e32",
          "md5": "7c8b3dd3514d0ced7f8f31dd6f89c15a"
        }
      ]
    }
  ]
}
